//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestadorServ.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServicoPrestadoSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicoPrestadoSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrestadorServ.Models.Resources.ServicoPrestadoSql", typeof(ServicoPrestadoSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.proc_fornecedor_sem_servico.
        /// </summary>
        internal static string FornecedoresSemResultados {
            get {
                return ResourceManager.GetString("FornecedoresSemResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.proc_media_servicos.
        /// </summary>
        internal static string MediaServicosPorFornecedorTipo {
            get {
                return ResourceManager.GetString("MediaServicosPorFornecedorTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.proc_maiores_clientes.
        /// </summary>
        internal static string MeloresConsumidores {
            get {
                return ResourceManager.GetString("MeloresConsumidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	ServicoPrestado.id_prestado as IdServicoPrestado,
        ///		ServicoPrestado.id_cliente as IdCliente,
        ///		ServicoPrestado.id_fornecedor as IdFornecedor,
        ///		ServicoPrestado.id_tipo_serv as IdTipoServico,
        ///		ServicoPrestado.desc_prestado as DescricaoServicoPrestado,
        ///		ServicoPrestado.dt_atend_prestado as DataAtendimentoServicoPrestado,
        ///		ServicoPrestado.valor_prestado as ValorServicoPrestado,
        ///
        ///		-- Cliente
        ///		Cliente.id_cliente as IdCliente,
        ///		Cliente.nome_cliente as NomeCliente,
        ///		Cliente.bairro_cliente  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObterServicoPrestado {
            get {
                return ResourceManager.GetString("ObterServicoPrestado", resourceCulture);
            }
        }
    }
}
